apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: scg-frontend
  labels:
    app.kubernetes.io/part-of: tanzu-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web-basic
    app.kubernetes.io/component: run
    carto.run/workload-name: scg-frontend
spec:
  template:
    metadata:
      annotations:
        conventions.apps.tanzu.vmware.com/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: tanzu-app
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web-basic
        carto.run/workload-name: scg-frontend
    spec:
      containers:
      - image: harbor.source-lab.io/tap/supply-chain/scg-frontend-dev@sha256:54d0f0b8239c718c3f72dd77726bf311160e072b07ad5d8717d2ac63b804f225
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

