apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: golang
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
  labels:
    app.kubernetes.io/part-of: tanzu-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web-basic
    app.kubernetes.io/component: run
    carto.run/workload-name: golang
spec:
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: tanzu-app
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web-basic
        carto.run/workload-name: golang
    spec:
      containers:
      - image: harbor.source-lab.io/tap/supply-chain/golang-dev@sha256:f0d49cbb81c5a74d0517974b3178a3d0b4805c84c694b742addaf42b03e042c5
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

