apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: golang
  labels:
    app.kubernetes.io/part-of: tanzu-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web-basic
    app.kubernetes.io/component: run
    carto.run/workload-name: golang
spec:
  template:
    metadata:
      annotations:
        conventions.apps.tanzu.vmware.com/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: tanzu-app
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web-basic
        carto.run/workload-name: golang
    spec:
      containers:
      - image: harbor.source-lab.io/tap/supply-chain/golang-dev@sha256:32ef9bfa17b172a14d44db86ecfd90b2bf3c74847bf243d863133253c0c495d0
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

