apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: forecast
  labels:
    app.kubernetes.io/part-of: tanzu-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: forecast
spec:
  template:
    metadata:
      annotations:
        conventions.apps.tanzu.vmware.com/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: tanzu-app
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: forecast
    spec:
      containers:
      - image: harbor.source-lab.io/tap/supply-chain/forecast-dev@sha256:9a321faabc6b5d7179c8cf65a5bea70ec153309bfa324b954fcc0eb53cd5b819
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

